apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: nginx-gateway
  namespace: <your-namespace>
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"



apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx-vs
  namespace: <your-namespace>
spec:
  hosts:
  - "*"
  gateways:
  - nginx-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx
        port:
          number: 80






apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-a
spec:
  hosts:
    - service-a.default.svc.cluster.local
  http:
    - route:
        - destination:
            host: service-a
      retries:
        attempts: 3
        perTryTimeout: 2s
        retryOn: "5xx"
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: service-b.default.svc.cluster.local
            port:
              number: 80
          headers:
            request:
              set:
                :path: /api/serviceb-endpoint  # Forward request to ServiceB API
